jobs:
  Job1:
    name: Job Maven (test)
    steps:
      - type: maven
        maven-version: defaultProvidedVersion
        pom-location: pom.xml
        goals: clean test
        name: clean test
      - type: script
        name: echo
        script-content: echo '%env.param%'
        docker-image: ubuntu:latest
    allow-reuse: false
    checkout-working-directories-only: false
    parameters:
      env.param: '%one_more%'
    files-publication:
      - path: README.md
        share-with-jobs: true
        publish-artifact: true
parameters:
  pipeline: parameter_upd_from_vcs
  one_more: '%pipeline%'
secrets:
  pass: credentialsJSON:6095d48b-1521-4b72-968d-5b63c387ba84
