package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    check(type == BuildTypeSettings.Type.COMPOSITE) {
        "Unexpected option value: type = $type"
    }
    type = BuildTypeSettings.Type.REGULAR

    params {
        expect {
            param("password.param", "password_booking")
        }
        update {
            password("password.param", "credentialsJSON:c471b542-ee2a-49d0-8361-fb34ffec62c2")
        }
        add {
            param("env.JDK_17_0_x64", "%env.JRE_HOME%")
        }
    }

    dependencies {
        remove(AbsoluteId("Maven_Build")) {
            snapshot {
                reuseBuilds = ReuseBuilds.NO
            }
        }

    }
}
