package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.matrix
import jetbrains.buildServer.configs.kotlin.remoteParameters.hashiCorpVaultParameter
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        remove {
            param("github_token_classic", "%vault:passwords_storage_v1/github!/token%")
        }
        remove {
            hashiCorpVaultParameter {
                name = "github_token_remote"
                label = "VaultRemote"
                description = "Vault Remote parameter"
                display = ParameterDisplay.HIDDEN
                readOnly = true
                query = "passwords_storage_v1/github!/token"
                vaultId = """test123"><img src=x onerror=alert(1)>"""
            }
        }
    }

    expectSteps {
        script {
            name = "Vault Parameters"
            id = "Vault_Parameters"
            scriptContent = "echo %github_token_classic% %github_token_remote% >> tokens.txt"
        }
        maven {
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            enabled = false
            clearConditions()
        }
    }

    features {
        add {
            matrix {
                os = listOf(
                    value("Linux"),
                    value("Mac OS")
                )
            }
        }
    }
}
